name: "BorgBackup"
description: "BorgBackup is a Hass Add-On - Fork by Tapchicoma, based on 3v1n0, yeah and frigi83"
version: "0.70.0"
slug: "borg_backup"
url: "https://github.com/Tapchicoma/hassio-borg_backup"
startup: once
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
host_network: false
hassio_role: "backup"
map:
  - backup:rw
options:
  user: null
  host: null
  port: 22
  path: "~"
  encryption: "repokey"
  archive: "hassio"
  passphrase: null
  create_options: "--stats --compression auto,zstd"
  prune_options: "--keep-daily=8 --keep-weekly=5 --keep-monthly=13"
  deduplicate_archives: true
  local_snapshot: 3
schema:
  user: str
  host: str
  port: port
  path: str
  encryption: str
  archive: str
  passphrase: password
  prune_options: "str?"
  create_options: "str?"
  deduplicate_archives: "bool"
  local_snapshot: "int(0,)?"
